theme: jekyll-theme-minimal
title: Entornos de Desarrollo.- UT4: Diseño y Realización de Pruebas
description: Unidad de Trabajo desarrollada para la parte B de la fase de oposición para la especialidad 107 Informática del Cuerpo de Profesores de Enseñanza Secundaria (0590) según RESOLUCIÓN de 19 de diciembre de 2022, de la Consejería de Educación, por la que se convocan procedimientos
selectivos extraordinarios de estabilización para el ingreso mediante concurso-oposición en los cuerpos de Profesores de Enseñanza Secundaria (0590), Profesores de Escuelas Oficiales de Idiomas (0592) y Maestros (0597) a que
se refiere la Ley Orgánica 2/2006, de 3 de mayo, de Educación.. 
logo: /logo.png
